version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
        container_name: elasticsearch
        volumes:
            - ./data-docker:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - elk
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.4
        ports:
            - '5601:5601'
        networks:
            - elk
        environment:
            XPACK_SECURITY_ENABLED: 'false'
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200

        depends_on:
            - elasticsearch
networks:
    elk:
        driver: bridge
